team_builder/accounts/urls.py
from django.conf.urls import url

from . import views
from . import endpoints


urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile_edit/$', views.profile_edit, name='profile_edit'),
    url(r'^profile/(?P<username>[_\d\w]+)/$', views.profile_other,
        name='profile_other'),
    # Endpoints
    url(r'^api/v1/signup/$', endpoints.signup, name='api_signup'),
    url(r'^api/v1/login/$', endpoints.login_user, name='api_login'),
    url(r'^api/v1/logout/$', endpoints.logout_user, name='api_logout'),
    url(r'^api/v1/profile/$', endpoints.profile, name='api_profile'),
    url(r'^api/v1/profile/(?P<username>[_\w]+)/$', endpoints.profile_other,
        name='api_profile_other'),
    url(r'^api/v1/avatar/$', endpoints.profile_avatar,
        name='api_profile_avatar'),

]

team_builder/projects/urls.py
from django.conf.urls import url

from . import views
from . import endpoints

urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^new', views.new_project, name='new'),
    url(r'^(?P<pk>\d+)/$', views.view_project, name='view'),
    url(r'^applications/$', views.view_applications, name='applications'),
    # Endpoints
    url(r'^api/v1/projects/$', endpoints.project_list, name='api_list'),
    url(r'^api/v1/project/(?P<pk>\d+)/$', endpoints.project,
        name='api_detail'),
    url(r'^api/v1/applications/$', endpoints.application_list,
        name='api_application_list'),
    url(r'^api/v1/application/(?P<pk>\d+)/$', endpoints.application_detail,
        name='api_application'),
]

team_builder/team_builder/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('projects.urls', namespace='projects')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team_builder/projects/models.py
from django.db import models
from django.conf import settings
from accounts import models as accounts_models


POSITION_STATUSES = (
    (0, 'vacant'),
    (1, 'filled')
)


class Position(models.Model):
    title = models.CharField(max_length=140)
    description = models.TextField(blank=True, default='')
    status = models.SmallIntegerField(
        choices=POSITION_STATUSES,
        blank=True,
        default=0
    )
    project = models.ForeignKey(
        'SiteProject',
        related_name='positions',
        on_delete=models.CASCADE
    )
    skill = models.ForeignKey(
        accounts_models.Skill,
        related_name='positions',
        null=True,
        blank=True
    )

    def __str__(self):
        return "{} for {}".format(self.title, str(self.project))


class SiteProject(models.Model):
    title = models.CharField(max_length=140)
    description = models.TextField()
    timeline = models.CharField(max_length=255)
    applicant_requirements = models.TextField(blank=True)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='site_projects'
    )

    def __str__(self):
        return self.title


APPLICATION_STATUSES = (
    (0, 'pending'),
    (1, 'accepted'),
    (2, 'rejected')
)


class Application(models.Model):
    position = models.ForeignKey(Position, related_name='applications')
    applicant = models.ForeignKey(settings.AUTH_USER_MODEL,
                                  related_name='applications')
    status = models.SmallIntegerField(choices=APPLICATION_STATUSES,
                                      blank=True,
                                      default=0)

    def __str__(self):
        return "{}: {} for {}".format(self.get_status_display(),
                                      self.applicant,
                                      self.position)

team_builder/projects/forms.py
from django.forms import forms, fields

from . import models
from accounts import models as accounts_models


class NewProjectForm(forms.Form):
    def __init__(self, project, owner, positions, *args, **kwargs):
        self.project = project
        self.owner = owner
        self.positions = positions
        super().__init__(*args, **kwargs)

    title = fields.CharField(max_length=140)
    description = fields.CharField()
    timeline = fields.CharField(max_length=255)
    applicant_requirements = fields.CharField()

    def save(self):
        if self.project is None:
            project = models.SiteProject.objects.create(owner=self.owner)
        else:
            project = self.project
        project.title = self.cleaned_data['title']
        project.description = self.cleaned_data['description']
        project.timeline = self.cleaned_data['timeline']
        project.applicant_requirements = self.cleaned_data[
            "applicant_requirements"]
        project.positions.all().delete()
        for title, description, skill in self.positions:
            try:
                skill_object = accounts_models.Skill.objects.get(name=skill)
            except accounts_models.Skill.DoesNotExist:
                skill_object = None
            models.Position.objects.create(
                title=title,
                description=description,
                status=0,
                project=project,
                skill=skill_object
            )
        project.save()

team_builder/projects/views.py
from django.shortcuts import (render, Http404, redirect, reverse,
                              get_object_or_404)
from django.db.models import Q
from . import forms
from . import models
from accounts import models as account_models


def index(request):
    search_term = request.GET.get('term')
    skill = request.GET.get('skill')
    if search_term:
        projects = models.SiteProject.objects.filter(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term)
        )
    elif skill:
        projects = models.SiteProject.objects.filter(
            positions__skill=skill
        )
    else:
        projects = models.SiteProject.objects.all()
    all_skills = account_models.Skill.objects.all()
    return render(request, 'index.html', context={
        'projects': projects,
        'all_skills': all_skills
    })


def new_project(request):
    if not request.user.is_authenticated():
        return Http404('Logged In user required')
    all_skills = account_models.Skill.objects.all()
    return render(request, 'project_new.html', context={
        'all_skills': all_skills
    })


def view_project(request, pk):
    project = get_object_or_404(models.SiteProject, pk=pk)
    if request.user.is_authenticated:
        applied_positions = models.Position.objects.filter(
            project=project).filter(applications__applicant=request.user)
    else:
        applied_positions = models.Position.objects.none()
    pending_positions = applied_positions.filter(applications__status=0)
    approved_positions = applied_positions.filter(applications__status=1)
    rejected_positions = applied_positions.filter(applications__status=2)
    return render(request, 'project.html', context={
        'project': project,
        'pending_positions': pending_positions,
        'approved_positions': approved_positions,
        'rejected_positions': rejected_positions
    })


def view_applications(request):
    skills = account_models.Skill.objects.all()
    applications = models.Application.objects.filter(
        position__project__owner=request.user)
    return render(request, 'applications.html', context={
        'all_skills': skills,
        'applications': applications
    })

team_builder/templates/applications.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a class="selected" href="{% url 'projects:applications' %}">Applications</a></li>
        <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
      </ul>
    </nav>
  </div>

  <div id='body' class="bounds circle--page">
    <div id='top' class="circle--page--header grid-100">
      <h2>Applications</h2>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Status</h4>
        <ul class="circle--filter--list">
          <li><a class="selected">All Applications</a></li>
          <li><a>New Applications</a></li>
          <li><a>Accepted</a></li>
          <li><a>Rejected</a></li>
        </ul>
      </div>

      <div class="circle--filter circle--secondary--module">
        <h4>My Projects</h4>
        <ul class="circle--filter--list">
          <li><a class="selected">All Projects</a></li>
          {% for project in user.site_projects.all %}
          <li><a>{{ project.title }}</a></li>
          {% endfor %}
        </ul>
      </div>

      <div class="circle--filter circle--secondary--module">
        <h4>Project Needs</h4>
        <ul class="circle--filter--list">
          <li><a class="selected">All Needs</a></li>
          {% for skill in all_skills %}
          <li><a>{{ skill.name }}</a></li>
          {% endfor %}
        </ul>
      </div>

    </div>

    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Applicant</th>
            <th class="circle--cell--right">Applicant Position</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for application in applications %}
          <tr id='{{ application.id }}' class="clickable-row" data-href="{% url 'accounts:profile_other' username=application.applicant.username %}">
            <td>
              <h3>
                {% if application.applicant.profile.name %}
                {{ application.applicant.profile.name }}
                {% else %}
                {{ application.applicant.username }}
                {% endif %}
              </h3>
              <p>{{ application.position.project.title }}</p>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">{{ application.position.title }}</span>
            </td>
            <td>
              {% if application.status != 1 %}
              <button class='button button-small approve-button'>Approve</button>
              {% endif %}
              {% if application.status != 2 %}
              <button class='button button-small reject-button'>Reject</button>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

    </div>

  </div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/js.cookie.js' %}"></script>
<script src="{% static 'js/utilities.js' %}"></script>
<script src="{% static 'js/application_view.js' %}" charset="utf-8"></script>
{% endblock %}

team_builder/templates/index.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Projects</h2>
      </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
        {% if user.is_authenticated %}
        <a class="button button-primary icon-on-left" href="{% url 'projects:new' %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 13 13" style="enable-background:new 0 0 13 13;" xml:space="preserve" class="add">
            <polygon points="7,6 7,0 6,0 6,6 0,6 0,7 6,7 6,13 7,13 7,7 13,7 13,6 "/>
          </svg>
          New Project
        </a>
        {% endif %}
      </div>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Project Needs</h4>
        <ul class="circle--filter--list">
          <li><a class="selected">All Needs</a></li>
          {% for skill in all_skills %}
          <li><a class='skill-filter'>{{ skill.name }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>

    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Project Needs</th>
          </tr>
        </thead>
        <tbody>
          {% for project in projects %}
          <tr class="clickable-row" data-href="{% url 'projects:view' pk=project.id %}">
            <td>
              <h3>{{ project.title }}</h3>
            </td>
            <td class="circle--cell--right">
              {% for position in project.positions.all %}
              <span class="secondary-label">{{ position.title }}</span><br>
              {% endfor %}
            </td>
          </tr>
          {% endfor %}
          </tr>
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/index.js' %}" charset="utf-8"></script>
{% endblock %}

team_builder/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset="utf-8">
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <title>{% block title %}Team Building Social Site{% endblock %}</title>
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>
    <header class="circle--header">
      <div class="bounds">
        <div class="circle--fluid">
          <div class="circle--fluid--cell">
            <h1 class="hide-text circle--logo"><a class="logo" href="{% url 'projects:home' %}">Circle</a></h1>
          </div>
          <div class="circle--fluid--cell circle--fluid--primary">
            <div class="circle--search">
              <input id='search-projects' type="text" placeholder="Search Projects..." />
              <button id='search-button'>
                <svg version="1.1" class="search" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 12 12" xml:space="preserve">
                  <path d="M12,10.6L8.3,6.9C8.7,6.2,9,5.4,9,4.5C9,2,7,0,4.5,0S0,2,0,4.5S2,9,4.5,9c0.9,0,1.7-0.3,2.4-0.7l3.7,3.7L12,10.6z M2,4.5
                  C2,3.1,3.1,2,4.5,2S7,3.1,7,4.5C7,5.9,5.9,7,4.5,7S2,5.9,2,4.5z"/>
                </svg>
              </button>
            </div>
          </div>
          <div class="circle--fluid--cell circle--fluid--secondary">
            <nav>
              <ul class="circle--inline">
                {% if user.is_authenticated %}
                  <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
                  <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                {% else %}
                  <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                  <li><a href="{% url 'accounts:signin' %}">Sign In</a></li>
                {% endif %}
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </header>

    {% block content %}
    {% endblock %}
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script type="text/javascript" src="{% static 'js/autogrow.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/global.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/utilities.js' %}"></script>
    <script>
      document.getElementById('search-projects').addEventListener('keyup', function (event) {
        if (event.keyCode == 13) {
          document.getElementById("search-button").click()
        }
      })
      document.getElementById('search-button').onclick = function () {
        utilities.goToSearchedProjectsPage()
      }
    </script>
    {% block scripts %}
    {% endblock %}
  </body>
</html>

team_builder/templates/profile.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a href="{% url 'projects:applications' %}">Applications</a></li>
        <li><a class="selected" href="{% url 'accounts:profile' %}">Profile</a></li>
      </ul>
    </nav>
  </div>

  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Profile</h2>
      </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
        <a class="button icon-on-left" href="{% url 'accounts:profile_edit' %}">Edit</a>
      </div>
    </div>

    <div class="grid-70">
      <h1>{{ user.profile.name }}</h1>
      <div class="circle--article--body">
        <p>{{ user.profile.bio }}</p>
      </div>

      <h2>Past Projects</h2>
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Project Needs</th>
          </tr>
        </thead>
        <tbody>
          {% for position in user.positions.all %}
          {% if position.status == 2 %}
          <tr class="clickable-row" data-href="{{ position.project.url }}" data-target="_blank">
            <td>
              <h3>{{ position.project.title }}</h3>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">{{ position.title }}</span>
            </td>
          </tr>
          {% endif %}
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
        <div class="circle--primary--avatar avatar-collapse">
          {% if user.profile.avatar %}
          <img class='profile-avatar' src="{{ user.profile.avatar.url }}" alt="user avatar">
          {% else %}
          <img class='profile-avatar' src="{% static 'images/default_avatar.svg' %}" alt="user avatar">
          {% endif %}
        </div>
      </div>

      <div class="circle--secondary--module">
        <h4>My Skills</h4>
        <ul class="unloaded">
          {% for skill in user.profile.skills.all %}
          <li>{{ skill.name }}</li>
          {% endfor %}
        </ul>
      </div>

      <div class="circle--secondary--module">
        <h4>My Projects</h4>
        <ul class="circle--link--list">
          {% for project in user.site_projects.all %}
          <li>
            <a href="{% url 'projects:view' pk=project.id %}">{{ project.title }}<br>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

team_builder/templates/profile_edit.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a href="{% url 'projects:applications' %}">Applications</a></li>
        <li><a class="selected" href="{% url 'accounts:profile' %}">Profile</a></li>
      </ul>
    </nav>
  </div>

  <form id='form' action="" method="post">
    {% csrf_token %}
  <div id='body' class="bounds circle--page">
    <div id='top' class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Profile</h2>
      </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
        <input type="submit" class="button button-primary icon-on-left" value="Save Changes">
      </div>
    </div>

    <div class="grid-70">
      <input id='name' name="name" type="text" value="{{ user.profile.name }}" placeholder="Full Name" class="circle--input--h1">
      <div class="circle--article--body">
        <textarea id='bio' name="bio" id="bio" placeholder="Tell us about yourself...">{{ user.profile.bio }}</textarea>
      </div>

      <h2>Past Projects</h2>
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Project Needs</th>
          </tr>
        </thead>
        <tbody>
          {% for position in user.positions.all %}
          {% if position.status == 2 %}
          <tr class="clickable-row" data-href="{{ position.project.url }}" data-target="_blank">
            <td>
              <h3>{{ position.project.title }}</h3>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">{{ position.title }}</span>
            </td>
          </tr>
          {% endif %}
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
        <div id='avatar' class="circle--primary--avatar"
        {% if user.profile.avatar %}
        style="background-image: url('{{ user.profile.avatar.url }}')"
        {% endif %}
        >
          <a id='upload-image-button' class="button">
            Upload Photo
            <input id='upload-image' type="file" accept='image/*'>
          </a>
        </div>
      </div>

      <div class="circle--secondary--module">
        <h4>My Skills</h4>
        <ul class="circle--clone--list">
          {% if user.profile.skills.all %}
            {% for skill in user.profile.skills.all %}
            <li>
              <select class='skills' name="skills">
                <option value="">-------</option>
                {% for skill_instance in all_skills %}
                <option value="{{ skill_instance.name }}"
                        {% if skill.name == skill_instance.name %}
                        selected
                        {% endif %}
                >{{ skill_instance.name }}</option>
                {% endfor %}
              </select>
              <a class="circle--clone--add">Add Skill</a>
              <a class="circle--clone--remove">Remove</a>
            </li>
            {% endfor %}
          {% else %}
            <li>
              <select class='skills' name="skills">
                <option value="">-------</option>
                {% for skill_instance in all_skills %}
                <option value="{{ skill_instance.name }}">{{ skill_instance.name }}</option>
                {% endfor %}
              </select>
              <a class="circle--clone--add">Add Skill</a>
              <a class="circle--clone--remove">Remove</a>
            </li>
          {% endif %}
        </ul>
      </div>

      <div class="circle--secondary--module">
        <h4>My Projects</h4>
        <ul class="circle--clone--list">
          {% for project in user.site_projects.all %}
          <li>
            {{ project.title }}<br>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  </form>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/js.cookie.js' %}" charset="utf-8"></script>
<script src="{% static 'js/utilities.js' %}" charset="utf-8"></script>
<script src="{% static 'js/profile_edit.js' %}" charset="utf-8"></script>
{% endblock %}

team_builder/templates/project_edit.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
  <form id='form' action="" method="post">
    {% csrf_token %}
  <div class="circle--actions--bar">
    <div class="bounds">
      <div class="grid-100">
        <input type="submit" class="button button-primary" value="Save Project">
        <a class="button button-text" href="{% url 'projects:home' %}">Discard</a>
      </div>
    </div>
  </div>

  {% if form_errors %}
    <h2 class="center-text">Error:</h2>
    {% for field, error in form_errors.items %}
    <div class="grid-30 centered">
      {{ field }}: {{ error }}
    </div>
    {% endfor %}
  {% endif %}
  <div class="bounds circle--page circle--article">
    <div class="grid-70">
      <div class="circle--article--body">
        <input name="title" type="text" class="circle--input--h1" placeholder="Project Title" value="{{ project.title }}">
        <textarea name="description" placeholder="Project description...">{{ project.description }}</textarea>
      </div>

      <div class="circle--project--positions">
        <h2>Positions</h2>

        <ul class="circle--group--list circle--clone--list">
          {% if project.positions %}
          {% for position in project.positions.all %}
          <li class='position-existing'>
            <input name="position_title" type="text" class="circle--input--h3" placeholder="Position Title" value="{{ position.title }}">
            <textarea name="position_description" placeholder="Position description...">{{ position.description }}</textarea>
            {% if all_skills %}
            <select name="skills">
              <option value="">-------</option>
              {% for skill in all_skills %}
              <option value="{{ skill.name }}" {% if skill == position.skill %} selected {% endif %}>{{ skill.name }}</option>
              {% endfor %}
            </select>
            {% endif %}
            <a class="circle--clone--add">Add Position</a>
            <a class="circle--clone--remove">Remove</a>
          </li>
          {% endfor %}
          {% else %}
          <li class='position-new'>
            <input name="position_title" type="text" class="circle--input--h3" placeholder="Position Title" />
            <textarea name="position_description" placeholder="Position description..."></textarea>
            {% if all_skills %}
            <select name="skills">
              <option value="">-------</option>
              {% for skill in all_skills %}
              <option value="{{ skill.name }}">{{ skill.name }}</option>
              {% endfor %}
            </select>
            {% endif %}
            <a class="circle--clone--add">Add Position</a>
            <a class="circle--clone--remove">Remove</a>
          </li>
          {% endif %}
        </ul>
        <input type="submit" class="button button-primary" value="Save Project">
      </div>
    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
        <h3>Project Timeline</h3>
        <textarea name='timeline' placeholder="Time estimate" class="circle--textarea--input">{{ project.timeline }}</textarea>
      </div>

      <div class="circle--secondary--module">
        <h3>Applicant Requirements</h3>
        <textarea name="applicant_requirements">{{ project.applicant_requirements }}</textarea>
      </div>

    </div>
  </div>
  </form>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/profile_edit.js' %}"></script>
{% endblock %}

team_builder/templates/project_new.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
  <form id='form' action="" method="post">
    {% csrf_token %}
  <div class="circle--actions--bar">
    <div class="bounds">
      <div class="grid-100">
        <input type="submit" class="button button-primary" value="Save Project">
        <a class="button button-text" href="{% url 'projects:home' %}">Discard</a>
      </div>
    </div>
  </div>

  {% if form_errors %}
    <h2 class="center-text">Error:</h2>
    {% for field, error in form_errors.items %}
    <div class="grid-30 centered">
      {{ field }}: {{ error }}
    </div>
    {% endfor %}
  {% endif %}
  <div id='body' class="bounds circle--page circle--article">
    <div id='top'  class="grid-70">
      <div class="circle--article--body">
        <input id='title' name="title" type="text" class="circle--input--h1" placeholder="Project Title" value="{{ project.title }}">
        <textarea id='description' name="description" placeholder="Project description...">{{ project.description }}</textarea>
      </div>

      <div class="circle--project--positions">
        <h2>Positions</h2>

        <ul class="circle--group--list circle--clone--list">
          {% if project.positions %}
          {% for position in project.positions.all %}
          <li class='position-existing position'>
            <input name="position_title" type="text" class="circle--input--h3 position_title" placeholder="Position Title" value="{{ position.title }}">
            <textarea class='position_description' name="position_description" placeholder="Position description...">{{ position.description }}</textarea>
            {% if all_skills %}
            <select class='position_skill' name="skills">
              <option value="">-------</option>
              {% for skill in all_skills %}
              <option value="{{ skill.name }}" {% if skill == position.skill %} selected {% endif %}>{{ skill.name }}</option>
              {% endfor %}
            </select>
            {% endif %}
            <a class="circle--clone--add">Add Position</a>
            <a class="circle--clone--remove">Remove</a>
          </li>
          {% endfor %}
          {% else %}
          <li class='position-new position'>
            <input name="position_title" type="text" class="circle--input--h3 position_title" placeholder="Position Title" />
            <textarea class='position_description' name="position_description" placeholder="Position description..."></textarea>
            {% if all_skills %}
            <select class='position_skill' name="skills">
              <option value="">-------</option>
              {% for skill in all_skills %}
              <option value="{{ skill.name }}">{{ skill.name }}</option>
              {% endfor %}
            </select>
            {% endif %}
            <a class="circle--clone--add">Add Position</a>
            <a class="circle--clone--remove">Remove</a>
          </li>
          {% endif %}
        </ul>
        <input type="submit" class="button button-primary" value="Save Project">
      </div>
    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
        <h3>Project Timeline</h3>
        <textarea id='timeline' name='timeline' placeholder="Time estimate" class="circle--textarea--input">{{ project.timeline }}</textarea>
      </div>

      <div class="circle--secondary--module">
        <h3>Applicant Requirements</h3>
        <textarea id='applicant_requirements' name="applicant_requirements">{{ project.applicant_requirements }}</textarea>
      </div>

    </div>
  </div>
  </form>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/js.cookie.js' %}"></script>
<script src="{% static 'js/utilities.js' %}"></script>
<script src="{% static 'js/project_new.js' %}"></script>
{% endblock %}

team_builder/templates/signin.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
  <div id='body' class="bounds">
    <div id='top' class="grid-30 centered">
      <h2>Sign In</h2>
      <form id='form' action="" method="post">
        {% csrf_token %}
        <input id='email' type="email" placeholder="Email Address" name="email" required>
        <input id='password' type="password" placeholder="Password" name="password" required>
        <input type="submit" class="button-primary" value="Sign In">
        <a class="button" href="{% url 'accounts:signup' %}">Sign Up</a>
      </form>
    </div>
  </div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/js.cookie.js' %}" charset="utf-8"></script>
<script src="{% static 'js/utilities.js' %}" charset="utf-8"></script>
<script src="{% static 'js/signin.js' %}" charset="utf-8"></script>
{% endblock %}